---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: acm-applications
  namespace: acm-configuration
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  pathname: https://gitea.apps.cluster-dgmq2.sandbox343.opentlc.com/lab-user/ilt-applications
  type: Git
  secretRef:
    name: ilt-gitea
