---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: etcd-encryption-placement
  namespace: acm-policies
spec:
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
