---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: acm-hibernator
  namespace: acm-subscriptions
spec:
  clusterSelector:
    matchLabels:
      local-cluster: 'true'
