---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: acm-hibernator
  namespace: acm-subscriptions
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: cluster-specific/acm-hibernator
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: acm-hibernator
spec:
  channel: acm-configuration/acm-applications
  placement:
    placementRef:
      kind: PlacementRule
      name: acm-hibernator
